CREATE TABLE ACCOUNT
(
    UUID INT(10) AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    NAME VARCHAR(16) NOT NULL,
    PRIMARY KEY(UUID)
);

INSERT INTO ACCOUNT(EMAIL, PASSWORD, NAME)
VALUES('red@ddi.com', '1234', 'red');

SELECT * FROM ACCOUNT;